# Generated by Django 2.1.3 on 2018-11-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artis',
            new_name='artist',
        ),
    ]
